import { useState } from "react";
import InsightCard from "./InsightCard";
import TrialCard from "./TrialCard";

// Build a portable Markdown copy of an answer for save/share (UX-6).
function toMarkdown(data) {
  const lines = [];
  if (data.overview) lines.push("## Overview", "", data.overview, "");
  if (data.abstain_reason) {
    lines.push("> " + data.abstain_reason, "");
    if (data.suggestion) lines.push("> " + data.suggestion, "");
  }
  if (data.insights?.length) {
    lines.push("## Research Insights", "");
    data.insights.forEach((ins, i) => {
      lines.push(`${i + 1}. ${ins.finding}${ins.unverified ? " _(unverified)_" : ""}`);
      (ins.source_details || []).forEach((s) => {
        const bits = [s.title, s.year, s.url].filter(Boolean).join(" — ");
        if (bits) lines.push(`   - ${bits}`);
      });
    });
    lines.push("");
  }
  if (data.trials?.length) {
    lines.push("## Clinical Trials", "");
    data.trials.forEach((t) => {
      lines.push(`- **${[t.title, t.nct_id, t.status].filter(Boolean).join(" · ")}**`);
      if (t.location) lines.push(`  - Location: ${t.location}`);
      const url = t.source_details?.[0]?.url;
      if (url) lines.push(`  - ${url}`);
    });
    lines.push("");
  }
  if (data.recommendations?.length) {
    lines.push("## Personalized Recommendations", "");
    data.recommendations.forEach((r) => lines.push(`- ${r}`));
    lines.push("");
  }
  lines.push("---", "_Generated by Curalink — AI-retrieved research, not medical advice. Verify with original sources._");
  return lines.join("\n");
}

export default function StructuredResponse({ data, onFollowUp }) {
  const [copied, setCopied] = useState(false);
  if (!data) return null;

  const { overview, insights, trials, recommendations, abstain_reason, pipelineMeta, follow_up_questions } = data;
  const warnings = pipelineMeta?.warnings || [];
  const hasSourceWarnings = warnings.some(
    (w) => w.includes("_failed") || w.includes("_timeout")
  );

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(toMarkdown(data));
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* clipboard blocked (non-secure context) — ignore */
    }
  };
  const handleDownload = () => {
    const blob = new Blob([toMarkdown(data)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "curalink-answer.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  // Abstain state
  if (abstain_reason) {
    return (
      <div className="structured-response abstain">
        <div className="overview">{overview}</div>
        <div className="abstain-reason">
          <span className="abstain-icon">i</span>
          <div>
            <p>{abstain_reason}</p>
            {data.suggestion && <p className="suggestion">{data.suggestion}</p>}
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="structured-response">
      <div className="response-actions">
        <button className="response-action-btn" onClick={handleCopy} title="Copy answer as Markdown">
          {copied ? "Copied!" : "Copy"}
        </button>
        <button className="response-action-btn" onClick={handleDownload} title="Download answer as Markdown">
          Download
        </button>
      </div>

      {/* Source warnings banner */}
      {hasSourceWarnings && (
        <div className="warning-banner">
          <span className="warning-icon">!</span>
          <p>
            Some data sources had issues. Results may be incomplete.
            {warnings
              .filter((w) => w.includes("_failed"))
              .map((w) => {
                const src = w.split("_failed")[0];
                return ` ${src} unavailable.`;
              })}
          </p>
        </div>
      )}

      {overview && (
        <div className="section overview-section">
          <h3>Overview</h3>
          <p>{overview}</p>
        </div>
      )}

      {insights && insights.length > 0 && (
        <div className="section insights-section">
          <h3>Research Insights</h3>
          {insights.map((ins, i) => (
            <InsightCard key={i} insight={ins} index={i} />
          ))}
        </div>
      )}

      {/* Empty insights state */}
      {(!insights || insights.length === 0) && !abstain_reason && (
        <div className="section empty-section">
          <h3>Research Insights</h3>
          <p className="empty-msg">No relevant publications found for this query.</p>
        </div>
      )}

      {trials && trials.length > 0 && (
        <div className="section trials-section">
          <h3>Clinical Trials</h3>
          {trials.map((trial, i) => (
            <TrialCard key={i} trial={trial} />
          ))}
        </div>
      )}

      {/* Empty trials state */}
      {(!trials || trials.length === 0) && !abstain_reason && (
        <div className="section empty-section">
          <h3>Clinical Trials</h3>
          <p className="empty-msg">No matching clinical trials found.</p>
        </div>
      )}

      {recommendations && recommendations.length > 0 && (
        <div className="section recommendations-section">
          <h3>Personalized Recommendations</h3>
          <ul className="recommendations-list">
            {recommendations.map((rec, i) => (
              <li key={i} className="recommendation-item">{rec}</li>
            ))}
          </ul>
        </div>
      )}

      {follow_up_questions && follow_up_questions.length > 0 && onFollowUp && (
        <div className="section follow-up-section">
          <h3>Follow-up Questions</h3>
          <div className="follow-up-chips">
            {follow_up_questions.map((q, i) => (
              <button key={i} className="follow-up-chip" onClick={() => onFollowUp(q)}>
                {q}
              </button>
            ))}
          </div>
        </div>
      )}

    </div>
  );
}
